services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - nextjs-demo-postgres-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_NAME" ]
      interval: 1s

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - nextjs-demopostgres-pgadmin-data:/var/lib/pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  nextjs-demo-postgres-db-data:
  nextjs-demopostgres-pgadmin-data:
